// frontend/src/settings/Settings.tsx
import React, {ChangeEvent, useState} from 'react';
import {Button, Form, FormCheck, Modal} from 'react-bootstrap';
import {LogLevel} from '../logs/LogData';

export interface SettingsProps {
    data: SettingsData,
    handleClose: () => void;
    handleSave: (data: SettingsData) => void
}

export interface SettingsData {
    apiUrl: string,
    apiKey: string,
    logLevel: string
}

export const Settings = (props: SettingsProps) => {
    const [apiUrl, setApiUrl] = useState(props.data.apiUrl);
    const [apiKey, setApiKey] = useState(props.data.apiKey);
    const [logLevel, setLogLevel] = useState(props.data.logLevel);

    const handleApiUrlChange = (event: ChangeEvent<HTMLInputElement>) => setApiUrl(event.target.value);
    const handleApiKeyChange = (event: ChangeEvent<HTMLInputElement>) => setApiKey(event.target.value);

    const logLevels = [LogLevel.DEBUG, LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR];

    return (
        <Modal show={true} onHide={props.handleClose} size={'lg'}>
            <Modal.Header closeButton>
                <Modal.Title>settings</Modal.Title>
            </Modal.Header>
            <Modal.Body>
                <Form>
                    <Form.Group controlId={'apiUrl'}>
                        <Form.Label>API URL</Form.Label>
                        <Form.Control type={'input'} placeholder={'API URL'} value={apiUrl} onChange={handleApiUrlChange}/>
                    </Form.Group>
                    <Form.Group controlId={'apiKey'}>
                        <Form.Label>API key</Form.Label>
                        <Form.Control type={'input'} placeholder={'API Key'} value={apiKey} onChange={handleApiKeyChange}/>
                    </Form.Group>
                    <Form.Group controlId={'logLevel'}>
                        <Form.Label>log level</Form.Label>
                        <div>
                            {logLevels.map((level, index) => (
                                <FormCheck inline name={'level'} type={'radio'}
                                           key={index}
                                           label={level.toLowerCase()}
                                           checked={level === logLevel}
                                           onChange={(evt) => setLogLevel(level)}
                                />
                            ))}
                        </div>
                    </Form.Group>
                </Form>
            </Modal.Body>
            <Modal.Footer>
                <Button variant="secondary" onClick={props.handleClose}>
                    close
                </Button>
                <Button variant="primary" onClick={() => props.handleSave({apiUrl, apiKey, logLevel})}>
                    save
                </Button>
            </Modal.Footer>
        </Modal>
    );
};

// frontend/src/app/settings/settings.component.ts
import {Component, OnInit} from "@angular/core";
import {LocalStorage} from "ngx-store";
import {LogData, LogLevel} from "../log/log-listener";
import {LogService} from "../log/log.service";

@Component({
    selector: "app-settings",
    templateUrl: "./settings.component.html",
    styleUrls: ["./settings.component.css"]
})
export class SettingsComponent implements OnInit {

    @LocalStorage()
    apiUrl: string = "";

    @LocalStorage()
    apiKey: string = "";

    logLevels: LogLevel[] = [LogLevel.DEBUG, LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR];

    @LocalStorage()
    logLevel: LogLevel = LogLevel.INFO;

    constructor(private logger: LogService) {
    }

    ngOnInit() {
    }

    logLevelSelected(logLevel: LogLevel) {
        this.logLevel = logLevel;
        this.logger.log(new LogData(this.logLevel, `setting LogLevel to ${this.logLevel}`));
    }
}

<div class="row" >
    <div class="border-bottom col-sm-12" id="settings">
        <form>
            <div class="form-group">
                <label for="ApiUrl">API URL</label>
                <input class="form-control" id="ApiUrl" placeholder="API URL"
                       name="apiUrl" [(ngModel)]="apiUrl">
            </div>
            <div class="form-group">
                <label for="ApiKey">API Key</label>
                <input class="form-control" id="ApiKey" placeholder="API Key"
                       name="apiKey" [(ngModel)]="apiKey">
            </div>
            <div>Log level</div>
            <div *ngFor="let level of logLevels" class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="loglevel" id="{{level}}" value="{{level}}"
                       [checked]="level === logLevel"
                (click)="logLevelSelected(level)">
                <label class="form-check-label" for="{{level}}">{{level | lowercase}}</label>
            </div>
        </form>
    </div>
</div>
